title: curatedMetagenomicData
short_title: cMD
description: Curated and processed metagenomic data through ExperimentHub

url: https://waldronlab.github.io/curatedMetagenomicData
baseurl: "waldronlab.github.io/curatedMetagenomicData"
paginate_path: "analyses/page:num/"
permalink: analyses/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Getting Started
   url: /getting-started
 - title: Analyses
   url: /analyses
 - title: Publications
   url: /publications

google_analytics: "UA-90028752-1"

github_url: https://github.com/waldronlab/curatedMetagenomicData
