title: curatedMetagenomicData
description: Curated and processed metagenomic data through ExperimentHub

url: https://waldronlab.github.io/curatedMetagenomicData
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

# social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
